[workspace]

members = [
    # Libraries

    # Binaries
    "hello_cargo",
    "guessing_game",
    "formatted_print",
    "concepts",
    "ownership",
    "structs",
]

resolver = "2"

[workspace.dependencies]

[patch.crates-io]
